name: Build Android Preview

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: 📦 Install EAS CLI & Dependencies
        run: |
          npm install -g eas-cli
          npm install --legacy-peer-deps

      - name: 🚀 Build APK Locally
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile preview --local --non-interactive --output=app-release.apk

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: alwaleed-app-binary
          path: app-release.apk
